// Shared constants for green observation system
// Used by both client components and API routes

import type { GreenIssueType } from "@/types/database";

export const greenIssueTypeLabels: Record<GreenIssueType, string> = {
  fungus_disease: "Fungus / Disease",
  dry_spot: "Dry Spot",
  wet_area: "Wet Area",
  bare_spot: "Bare Spot",
  weed_pressure: "Weed Pressure",
  pest_damage: "Pest Damage",
  mechanical_damage: "Mechanical Damage",
  irrigation_issue: "Irrigation Issue",
  algae: "Algae",
  frost_damage: "Frost Damage",
  ball_marks: "Ball Marks",
  scalping: "Scalping",
  compaction: "Compaction",
  thatch_buildup: "Thatch Buildup",
  aeration_needed: "Aeration Needed",
  topdressing_needed: "Topdressing Needed",
  moss: "Moss",
  shade_stress: "Shade Stress",
  traffic_wear: "Traffic Wear",
  chemical_burn: "Chemical Burn",
  poor_drainage: "Poor Drainage",
  uneven_surface: "Uneven Surface",
  other: "Other",
};

export const greenIssueTypeIcons: Record<GreenIssueType, string> = {
  fungus_disease: "🍄",
  dry_spot: "☀️",
  wet_area: "💧",
  bare_spot: "🟫",
  weed_pressure: "🌿",
  pest_damage: "🐛",
  mechanical_damage: "⚙️",
  irrigation_issue: "💦",
  algae: "🟢",
  frost_damage: "❄️",
  ball_marks: "⛳",
  scalping: "✂️",
  compaction: "🔨",
  thatch_buildup: "🧹",
  aeration_needed: "🕳️",
  topdressing_needed: "🏖️",
  moss: "🌲",
  shade_stress: "🌑",
  traffic_wear: "👣",
  chemical_burn: "🧪",
  poor_drainage: "🌊",
  uneven_surface: "📐",
  other: "📍",
};

/** Default descriptions auto-filled when an issue type is selected. User can edit freely. */
export const greenIssueTypeDescriptions: Record<GreenIssueType, string> = {
  fungus_disease: "Possible fungal infection on putting surface — discolored or damaged turf observed.",
  dry_spot: "Dry area on green — localized dry spot causing firmness or discoloration.",
  wet_area: "Wet/saturated area on putting surface — soft footing or standing water.",
  bare_spot: "Bare or thin area on green — exposed soil or sand with no turf coverage.",
  weed_pressure: "Weed encroachment on putting surface — Poa or other undesirable species present.",
  pest_damage: "Possible pest damage on green — irregular turf damage patterns observed.",
  mechanical_damage: "Mechanical damage to putting surface — mower tracking, scalp mark, or equipment damage.",
  irrigation_issue: "Irrigation problem on green — head malfunction, coverage gap, or leak detected.",
  algae: "Algae growth on putting surface — green/black film reducing turf health.",
  frost_damage: "Frost damage on green — turf discoloration or cell damage from freezing.",
  ball_marks: "Unrepaired ball marks — multiple impact craters affecting putting surface smoothness.",
  scalping: "Mower scalping damage — turf cut too low, exposed crowns or soil visible.",
  compaction: "Soil compaction on green — reduced infiltration and root growth observed.",
  thatch_buildup: "Excessive thatch layer — spongy surface affecting ball roll consistency.",
  aeration_needed: "Green needs aeration — compacted soil, poor drainage, or reduced rooting depth.",
  topdressing_needed: "Topdressing needed — surface irregularities or organic matter buildup.",
  moss: "Moss growth on putting surface — typically in shaded or wet areas.",
  shade_stress: "Shade stress — reduced turf density due to limited sunlight exposure.",
  traffic_wear: "Traffic wear pattern — thinning turf from concentrated foot traffic.",
  chemical_burn: "Chemical burn damage — yellowing or browning from fertilizer or pesticide application.",
  poor_drainage: "Drainage issue on green — water pooling or slow percolation after rain/irrigation.",
  uneven_surface: "Uneven putting surface — bumps, depressions, or settling affecting ball roll.",
  other: "",
};

/** Default fix instructions auto-filled when an issue type is selected. User can edit freely. */
export const greenIssueTypeFixTemplates: Record<GreenIssueType, string> = {
  fungus_disease: "1. Identify disease type (dollar spot, pythium, brown patch, etc.)\n2. Apply curative fungicide per label rates\n3. Reduce leaf wetness — adjust irrigation to early morning\n4. Raise mowing height temporarily if severe\n5. Monitor daily for 7-10 days",
  dry_spot: "1. Hand-water affected area with hose or syringe\n2. Probe soil to confirm dry conditions at root zone\n3. Apply wetting agent to hydrophobic spots\n4. Check irrigation head coverage and run times\n5. Monitor soil moisture daily until resolved",
  wet_area: "1. Check for irrigation leaks or broken heads nearby\n2. Inspect internal drainage — clear blocked drains\n3. Vent with solid tines to improve infiltration\n4. Reduce irrigation run time for this zone\n5. Consider adding surface drainage if chronic",
  bare_spot: "1. Determine cause (traffic, disease, scalping)\n2. Lightly scarify and apply seed or plugs\n3. Topdress with green-grade sand\n4. Keep consistently moist until establishment\n5. Use ball mark repair tool to protect new growth",
  weed_pressure: "1. Identify weed species (Poa annua, clover, etc.)\n2. Hand-remove if isolated patches\n3. Apply selective herbicide if widespread (check green-safe label)\n4. Overseed with bentgrass/bermuda to fill gaps\n5. Adjust cultural practices to favor desired species",
  pest_damage: "1. Identify pest type (cutworms, grubs, etc.)\n2. Soap flush test to check population\n3. Apply labeled insecticide for putting greens\n4. Water in if systemic product\n5. Monitor nightly for 5-7 days",
  mechanical_damage: "1. Assess depth and extent of damage\n2. Repair with green-grade sand and seed\n3. Adjust mower settings — check bench height\n4. Smooth area with level bar if needed\n5. Reduce mowing frequency on damaged area until healed",
  irrigation_issue: "1. Identify specific head or zone affected\n2. Check for clogged nozzles or broken risers\n3. Replace damaged components\n4. Run manual cycle to verify fix\n5. Adjust arc and radius for full green coverage",
  algae: "1. Improve surface drainage and air circulation\n2. Reduce irrigation frequency\n3. Apply labeled algaecide for greens\n4. Vent with solid tines\n5. Address shade issues — consider selective tree trimming",
  frost_damage: "1. Keep ALL traffic off green until frost melts completely\n2. Delay mowing until turf has recovered\n3. Do not irrigate while frost is present\n4. Apply light iron application once growth resumes\n5. Monitor for secondary disease entry",
  ball_marks: "1. Repair all visible ball marks with proper technique\n2. Educate golfers via signage at tee box\n3. Assign crew to walk greens and repair mid-round\n4. Consider firmer conditions to reduce impact depth\n5. Monitor high-traffic greens more frequently",
  scalping: "1. Raise mowing height immediately (1-2 notches)\n2. Verify mower bench height and reel sharpness\n3. Topdress lightly to protect exposed crowns\n4. Avoid double-cutting until recovery\n5. Check for surface undulations causing low spots",
  compaction: "1. Schedule core aeration or deep-tine aeration\n2. Solid-tine vent in interim for immediate relief\n3. Apply penetrant/wetting agent\n4. Topdress after aeration with green-grade sand\n5. Restrict cart traffic near greens",
  thatch_buildup: "1. Schedule verticutting or light dethatching\n2. Core aerate and remove plugs\n3. Heavy topdress with sand to dilute organic layer\n4. Increase mowing frequency temporarily\n5. Adjust fertilization to reduce excessive growth",
  aeration_needed: "1. Schedule core aeration — coordinate with tournament calendar\n2. Select appropriate tine size for conditions\n3. Topdress heavily with kiln-dried sand after\n4. Drag and roll to smooth surface\n5. Allow 7-14 days recovery before normal play",
  topdressing_needed: "1. Select green-grade sand matching existing rootzone\n2. Apply light dusting (1/8 - 1/4 inch)\n3. Drag with brush or mat to work into canopy\n4. Irrigate lightly to settle sand\n5. Mow at normal height once sand is incorporated",
  moss: "1. Improve light exposure — trim overhanging branches\n2. Improve air circulation with fans if available\n3. Apply moss-control product per label\n4. Aerate to improve surface drainage\n5. Adjust fertilization to favor turf over moss",
  shade_stress: "1. Evaluate tree canopy — schedule selective pruning\n2. Raise mowing height in shaded areas\n3. Apply iron-based fertilizer for color\n4. Reduce traffic in affected areas\n5. Consider shade-tolerant cultivars for renovation",
  traffic_wear: "1. Re-route foot traffic — move pin position\n2. Adjust cart path signage to spread entry points\n3. Rope off worn areas for recovery\n4. Overseed with wear-tolerant cultivar\n5. Topdress and keep moist until establishment",
  chemical_burn: "1. Irrigate heavily to flush product from rootzone\n2. Raise mowing height temporarily\n3. Apply foliar iron for color recovery\n4. Avoid additional chemical applications for 7-10 days\n5. Document application details for records",
  poor_drainage: "1. Inspect internal drainage system — check outlets\n2. Clear blocked drain lines with water jet\n3. Solid-tine vent to improve infiltration\n4. Consider channel drains if surface ponding\n5. Monitor after next rain event",
  uneven_surface: "1. Identify bumps and depressions\n2. Topdress low spots with green-grade sand\n3. Roll with lightweight roller if appropriate\n4. Core aerate and topdress to level over time\n5. Schedule level-bar smoothing during maintenance window",
  other: "",
};
