// Shared constants for hole observation system
// Used by both client components and API routes

import type { HoleIssueType } from "@/types/database";

export const issueTypeLabels: Record<HoleIssueType, string> = {
  fungus_disease: "Fungus / Disease",
  dry_spot: "Dry Spot",
  wet_area: "Wet Area",
  bare_spot: "Bare Spot",
  weed_pressure: "Weed Pressure",
  pest_damage: "Pest Damage",
  grub_damage: "Grub Damage",
  mulch_pile: "Mulch Pile",
  sticks_around_tree: "Sticks Around Tree",
  sticks_on_ground: "Sticks on Ground",
  felled_tree: "Felled Tree",
  mechanical_damage: "Mechanical Damage",
  drainage: "Drainage Issue",
  bunker_issue: "Bunker Issue",
  tree_issue: "Tree Issue",
  irrigation_issue: "Irrigation Issue",
  turf_thin: "Thin Turf",
  algae: "Algae",
  frost_damage: "Frost Damage",
  other: "Other",
};

export const issueTypeIcons: Record<HoleIssueType, string> = {
  fungus_disease: "🍄",
  dry_spot: "☀️",
  wet_area: "💧",
  bare_spot: "🟫",
  weed_pressure: "🌿",
  pest_damage: "🐛",
  grub_damage: "🪲",
  mulch_pile: "🪵",
  sticks_around_tree: "🌳",
  sticks_on_ground: "🪵",
  felled_tree: "🪓",
  mechanical_damage: "⚙️",
  drainage: "🌊",
  bunker_issue: "⛳",
  tree_issue: "🌳",
  irrigation_issue: "💦",
  turf_thin: "🌱",
  algae: "🟢",
  frost_damage: "❄️",
  other: "📍",
};

/** Default descriptions auto-filled when an issue type is selected. User can edit freely. */
export const issueTypeDescriptions: Record<HoleIssueType, string> = {
  fungus_disease: "Possible fungal infection — discolored or damaged turf observed.",
  dry_spot: "Dry area identified — turf showing signs of moisture stress and discoloration.",
  wet_area: "Persistently wet/saturated area — standing water or soggy turf conditions.",
  bare_spot: "Bare or thin area — exposed soil with little to no turf coverage.",
  weed_pressure: "Weed encroachment identified — undesirable plant material present in turf.",
  pest_damage: "Possible pest damage — irregular turf damage patterns observed.",
  grub_damage: "Grub damage — spongy turf that lifts easily, brown patches, or animal digging activity.",
  mulch_pile: "Pile of mulch that needs to be spread or removed.",
  sticks_around_tree: "Sticks and debris accumulated around tree base — needs cleanup.",
  sticks_on_ground: "Sticks and debris on the ground — needs cleanup for playability and mowing.",
  felled_tree: "Felled or fallen tree — needs removal or processing.",
  mechanical_damage: "Mechanical damage to turf — caused by mower, equipment, or vehicle traffic.",
  drainage: "Drainage issue — water not flowing properly, pooling, or erosion present.",
  bunker_issue: "Bunker maintenance needed — sand contamination, washout, or edge repair required.",
  tree_issue: "Tree-related issue — dead limbs, root damage, or canopy concerns.",
  irrigation_issue: "Irrigation problem — head malfunction, coverage gap, or leak detected.",
  turf_thin: "Thin turf area — reduced density, needs overseeding or recovery time.",
  algae: "Algae growth present — green/black film on turf surface, typically in wet areas.",
  frost_damage: "Frost damage observed — turf discoloration or cell damage from freezing.",
  other: "",
};

/** Default fix instructions auto-filled when an issue type is selected. User can edit freely. */
export const issueTypeFixTemplates: Record<HoleIssueType, string> = {
  fungus_disease: "1. Identify disease type (dollar spot, brown patch, etc.)\n2. Contact spray contractor to schedule fungicide application per label rates\n3. Reduce leaf wetness — adjust irrigation timing\n4. Monitor area daily for 7-10 days",
  dry_spot: "1. Check irrigation head coverage and rotation\n2. Hand-water affected area immediately\n3. Probe soil to confirm dry conditions at root zone\n4. Apply wetting agent if hydrophobic\n5. Adjust run times or add head if coverage gap",
  wet_area: "1. Check for irrigation leaks or broken heads\n2. Inspect drainage — clear any blocked drains\n3. Aerate area to improve infiltration\n4. Reduce irrigation run time for this zone\n5. Monitor after next rain event",
  bare_spot: "1. Determine cause (traffic, disease, scalping, etc.)\n2. Loosen soil and apply seed or sod\n3. Topdress lightly with sand/soil mix\n4. Keep moist until establishment\n5. Rope off area if high-traffic",
  weed_pressure: "1. Identify weed species\n2. Hand-pull isolated patches if small area\n3. For chemical treatment: contact spray contractor to schedule herbicide application (pre or post-emergent)\n4. Overseed thin areas to crowd out weeds",
  pest_damage: "1. Identify pest (armyworms, mole crickets, chinch bugs, etc.)\n2. Check population threshold — soap flush test\n3. Contact spray contractor to schedule insecticide application per label\n4. Water in after application if systemic product\n5. Monitor for 5-7 days after application",
  grub_damage: "1. Confirm grub presence — cut 1 sq ft turf section and check for white grubs at root zone\n2. Count grubs per sq ft (threshold: 8-10+ per sq ft)\n3. Contact spray contractor to schedule grub control insecticide application\n4. Water in heavily after application to move product into root zone\n5. Reseed or resod severely damaged areas\n6. Monitor for animal activity (skunks, raccoons digging for grubs)\n7. Re-check in 14 days to confirm population reduction",
  mulch_pile: "1. Assess pile size and location\n2. Spread mulch to appropriate depth (2-3 inches) around beds or trees\n3. Keep mulch 3-6 inches away from tree trunks\n4. Remove excess mulch from site if not needed\n5. Clean up surrounding area",
  sticks_around_tree: "1. Gather all sticks and debris from around tree base\n2. Check for dead or hanging branches that may drop more\n3. Haul debris to brush pile or disposal area\n4. Clean up area for mower access",
  sticks_on_ground: "1. Walk area and collect all sticks and debris\n2. Check for source — dead branches overhead\n3. Haul debris to brush pile or disposal area\n4. Clear area for safe mowing",
  felled_tree: "1. Assess size and safety — determine if chainsaw work is needed\n2. Section trunk and large limbs for removal\n3. Chip brush and small branches\n4. Remove stump or mark for grinding\n5. Repair any turf damage from the fall\n6. Schedule arborist if large-scale work required",
  mechanical_damage: "1. Assess extent of damage\n2. Repair divots — fill with sand/seed mix\n3. Adjust mower height or pattern if scalping\n4. Rope off area if needed for recovery\n5. Address root cause (operator training, equipment adjustment)",
  drainage: "1. Identify water flow pattern\n2. Clear any blocked catch basins or drains\n3. Check pipe integrity for breaks or clogs\n4. Consider adding French drain if chronic\n5. Re-grade surface to direct water flow",
  bunker_issue: "1. Assess sand depth and contamination level\n2. Rebuild edges if eroded\n3. Add fresh sand if below 4-inch depth\n4. Check drain function at bunker floor\n5. Rake and finish to playable condition",
  tree_issue: "1. Assess tree health and safety risk\n2. Remove dead or hanging limbs\n3. Treat root damage if exposed\n4. Consider canopy thinning for turf health\n5. Schedule arborist if major work needed",
  irrigation_issue: "1. Identify specific head or zone affected\n2. Check for clogged nozzles or broken risers\n3. Replace damaged components\n4. Run manual cycle to verify fix\n5. Adjust arc and radius for proper coverage",
  turf_thin: "1. Determine cause of thinning\n2. Core aerate to reduce compaction\n3. Overseed with appropriate blend\n4. Topdress with sand/compost mix\n5. Reduce traffic and mowing frequency until recovery",
  algae: "1. Improve drainage in affected area\n2. Reduce irrigation frequency\n3. Contact spray contractor to schedule algaecide application\n4. Aerate to improve air circulation at surface\n5. Address shade issues if applicable",
  frost_damage: "1. Keep traffic off affected areas until thaw\n2. Do not mow until turf has fully recovered\n3. Delay irrigation until ground thaws\n4. Apply light fertilizer once growth resumes\n5. Monitor for secondary disease entry",
  other: "",
};
