-- ============================================================================
-- Bar and Buckleys vendor receipts, Oct 2025 to Sep 2026 (2026-10-10).
--
-- Typed in from the scanned delivery receipts in Google Drive and the MWR
-- warehouse order history, checked line by line against each receipt (and
-- against the running account balance Lakeshore prints on every receipt).
--   Lakeshore Beverage      27 invoices  Oct 6 2025 to Apr 8 2026
--   Kloss Distributing       5 invoices and 2 credits  Nov 2025 to May 2026
--   MWR Central Warehouse    8 orders    Jun to Sep 2026
--   Mess requisitions        4 transfers from Epicenter  May to Jul 2026
-- Beer and liquor go to the bar (20091 / 151120). Sodas, water and food go to
-- the restaurant (20091 / 151110) and can be moved to the bar on the
-- Purchases page. Supplies are 20091 / 701000 or 701005.
--
-- This is data, not a schema change. Run it once in the Supabase SQL editor
-- after 20261007120000_bar_and_invoice_coding.sql. Running it again adds
-- nothing (an invoice already saved is skipped).
-- Generated by src/__tests__/restaurant/vendor-receipts.test.ts
-- ============================================================================

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-10-06', 'Lakeshore Beverage', 149.67, 'invoice', '311506', NULL, 0, 149.67, 0, 149.67, 'Invoice 311506 · 6 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 1, 'CS', 38.48, 38.48, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-06144', 'BHC MILL DONUT', '4/6/12 CAN', 1, 'CS', 35.38, 35.38, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-11182', 'BUD', '18/16 CAN', 1, 'CS', 19.73, 19.73, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-13045', 'PABST', '4/6/16 CAN', 1, 'CS', 22.6, 22.6, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-80079', 'POINT AMBER', '2/12/12 CAN', 1, 'CS', 23.48, 23.48, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-10-06', 'Lakeshore Beverage', 549.65, 'invoice', '311507', NULL, 0, 549.65, 0, 549.65, 'Invoice 311507 · 4 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 3, 'CS', 57.47, 172.41, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 3, 'CS', 52.46, 157.38, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581224', 'CUT PEPERMINT', '6/4/12', 2, 'CS', 57.47, 114.94, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-10-30', 'Lakeshore Beverage', 1116.69, 'invoice', '358300', NULL, 0, 1116.69, 0, 1116.69, 'Invoice 358300 · 8 items · Total from the items only, since the bottom of the receipt is not in the photo. Peppermint (2 cases) was out of stock. Another Oct 30 invoice of about $306.54 is not in the photos.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 3, 'CS', 57.47, 172.41, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 3, 'CS', 52.46, 157.38, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 3, 'CS', 52.46, 157.38, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581214', 'CUT PINE MARG', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581113', 'CUT TIKI MAI T', '6/4/12 CAN', 3, 'CS', 52.46, 157.38, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-581115', 'CUT VODKA MULE', '6/4/12 CAN', 3, 'CS', 52.46, 157.38, 'alcohol', 'bar', '20091', '151120'),
  (8, 'LSB-581202', 'CUT WHITE RUSS', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-11-12', 'Lakeshore Beverage', 317.02, 'invoice', '380981', NULL, 0, 317.02, 0, 317.02, 'Invoice 380981 · 7 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 2, 'CS', 38.48, 76.96, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-80224', 'BHC BLK PHILLI', '4/6/12 CAN', 2, 'CS', 35.38, 70.76, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-06144', 'BHC MILL DONUT', '4/6/12 CAN', 1, 'CS', 35.38, 35.38, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-80533', 'BHC POM FIZZ', '4/6/12 CAN', 2, 'CS', 35.43, 70.86, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-11182', 'BUD', '18/16 CAN', 1, 'CS', 19.73, 19.73, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-91568', 'GI HONKERS ALE', '2/12/12 CAN', 1, 'CS', 33.33, 33.33, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-11-12', 'Lakeshore Beverage', 372.23, 'invoice', '380983', NULL, 0, 372.23, 0, 372.23, 'Invoice 380983 · 4 items · Total worked out from Lakeshore running account balance on later receipts. Espresso Martini and Peppermint were out of stock.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 1, 'CS', 57.47, 57.47, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581202', 'CUT WHITE RUSS', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-11-19', 'Lakeshore Beverage', 174.64, 'invoice', '393156', NULL, 0, 174.64, 0, 174.64, 'Invoice 393156 · 7 items · Total printed on the invoice. Point Amber was out of stock.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-11182', 'BUD', '18/16 CAN', 1, 'CS', 19.73, 19.73, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-91568', 'GI HONKERS ALE', '2/12/12 CAN', 1, 'CS', 33.33, 33.33, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-99563', 'GI SOFIE', '4/6/12 CAN', 1, 'CS', 36.37, 36.37, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-80085', 'POINT MID BLCK', '2/12/12 CAN', 1, 'CS', 23.48, 23.48, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-88016', 'SHINER BOCK', '24/16 CAN', 1, 'CS', 27.5, 27.5, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-80360', 'SHINER HOL CHE', '2/12/12 BTL', 1, 'CS', 24.23, 24.23, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-11-19', 'Lakeshore Beverage', 697.06, 'invoice', '393158', NULL, 0, 697.06, 0, 697.06, 'Invoice 393158 · 6 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581225', 'CUT ESP MARTIN', '6/4/12', 5, 'CS', 52.47, 262.35, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 3, 'CS', 57.47, 172.41, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581214', 'CUT PINE MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-12-03', 'Lakeshore Beverage', 336.63, 'invoice', '417452', NULL, 0, 336.63, 0, 336.63, 'Invoice 417452 · 9 items · Total printed on the invoice. Black Philly was out of stock.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 1, 'CS', 38.48, 38.48, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-11182', 'BUD', '18/16 CAN', 1, 'CS', 19.73, 19.73, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-99785', 'GI BH TROPICAL', '2/12/12 CAN', 2, 'CS', 35.52, 71.04, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-80079', 'POINT AMBER', '2/12/12 CAN', 1, 'CS', 23.48, 23.48, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-80085', 'POINT MID BLCK', '2/12/12 CAN', 2, 'CS', 23.48, 46.96, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-80082', 'POINT SNOW PIL', '2/12/12 CAN', 1, 'CS', 23.48, 23.48, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-88016', 'SHINER BOCK', '24/16 CAN', 2, 'CS', 27.5, 55, 'alcohol', 'bar', '20091', '151120'),
  (8, 'LSB-80360', 'SHINER HOL CHE', '2/12/12 BTL', 2, 'CS', 24.23, 48.46, 'alcohol', 'bar', '20091', '151120'),
  (9, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-12-03', 'Lakeshore Beverage', 592.09, 'invoice', '417455', NULL, 0, 592.09, 0, 592.09, 'Invoice 417455 · 6 items · Total printed on the invoice. Long Island (2) and White Russian (3) were out of stock.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 3, 'CS', 57.47, 172.41, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 3, 'CS', 52.46, 157.38, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581113', 'CUT TIKI MAI T', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581115', 'CUT VODKA MULE', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-12-10', 'Lakeshore Beverage', 94.6, 'invoice', '429119', NULL, 0, 94.6, 0, 94.6, 'Invoice 429119 · 4 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-11182', 'BUD', '18/16 CAN', 1, 'CS', 19.73, 19.73, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-99785', 'GI BH TROPICAL', '2/12/12 CAN', 1, 'CS', 35.52, 35.52, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-07414', 'STELLA', '2/12/11.2 BTL', 1, 'CS', 29.35, 29.35, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-12-10', 'Lakeshore Beverage', 229.86, 'invoice', '429121', NULL, 0, 229.86, 0, 229.86, 'Invoice 429121 · 2 items · Total printed on the invoice. A third Dec 10 invoice for $58.00 is not in the photos.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 2, 'CS', 57.47, 114.94, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 2, 'CS', 57.46, 114.92, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-12-17', 'Lakeshore Beverage', 195.02, 'invoice', '441601', NULL, 0, 195.02, 0, 195.02, 'Invoice 441601 · 6 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 1, 'CS', 38.48, 38.48, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-93544', 'GI IPA', '6/4/16 CAN', 1, 'CS', 38.71, 38.71, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-80082', 'POINT SNOW PIL', '2/12/12 CAN', 1, 'CS', 23.48, 23.48, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-88016', 'SHINER BOCK', '24/16 CAN', 2, 'CS', 27.5, 55, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-07414', 'STELLA', '2/12/11.2 BTL', 1, 'CS', 29.35, 29.35, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-12-17', 'Lakeshore Beverage', 477.17, 'invoice', '441602', NULL, 0, 477.17, 0, 477.17, 'Invoice 441602 · 6 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581225', 'CUT ESP MARTIN', '6/4/12', 2, 'CS', 52.47, 104.94, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 1, 'CS', 57.47, 57.47, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581115', 'CUT VODKA MULE', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581202', 'CUT WHITE RUSS', '6/4/12 CAN', 3, 'CS', 52.46, 157.38, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-01-07', 'Lakeshore Beverage', 227.08, 'invoice', '474004', NULL, 0, 227.08, 0, 227.08, 'Invoice 474004 · 5 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 1, 'CS', 38.48, 38.48, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-80224', 'BHC BLK PHILLI', '4/6/12 CAN', 2, 'CS', 35.38, 70.76, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-99785', 'GI BH TROPICAL', '2/12/12 CAN', 2, 'CS', 35.52, 71.04, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-02462', 'GUINNESS', '3/8/14.9 CAN', 1, 'CS', 36.8, 36.8, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-01-07', 'Lakeshore Beverage', 319.77, 'invoice', '474005', NULL, 0, 319.77, 0, 319.77, 'Invoice 474005 · 6 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 1, 'CS', 57.47, 57.47, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581113', 'CUT TIKI MAI T', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-01-21', 'Lakeshore Beverage', 116.31, 'invoice', '497432', NULL, 0, 116.31, 0, 116.31, 'Invoice 497432 · 4 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 1, 'CS', 38.48, 38.48, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-80516', 'BHC TROP MANGO', '4/6/12 CAN', 1, 'CS', 38.48, 38.48, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-07414', 'STELLA', '2/12/11.2 BTL', 1, 'CS', 29.35, 29.35, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-01-21', 'Lakeshore Beverage', 319.77, 'invoice', '497433', NULL, 0, 319.77, 0, 319.77, 'Invoice 497433 · 5 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 1, 'CS', 57.47, 57.47, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 2, 'CS', 52.46, 104.92, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581113', 'CUT TIKI MAI T', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581115', 'CUT VODKA MULE', '6/4/12 CAN', 1, 'CS', 52.46, 52.46, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-02-04', 'Lakeshore Beverage', 123.28, 'invoice', '520501', NULL, 0, 123.28, 0, 123.28, 'Invoice 520501 · 3 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 2, 'CS', 38.48, 76.96, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-99785', 'GI BH TROPICAL', '2/12/12 CAN', 1, 'CS', 36.32, 36.32, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-02-04', 'Lakeshore Beverage', 493.34, 'invoice', '520502', NULL, 0, 493.34, 0, 493.34, 'Invoice 520502 · 6 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 1, 'CS', 59.26, 59.26, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581209', 'CUT VOD TRANS', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581202', 'CUT WHITE RUSS', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-02-18', 'Lakeshore Beverage', 201.31, 'invoice', '543832', NULL, 0, 201.31, 0, 201.31, 'Invoice 543832 · 4 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 2, 'CS', 38.48, 76.96, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-80516', 'BHC TROP MANGO', '4/6/12 CAN', 2, 'CS', 38.48, 76.96, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-02462', 'GUINNESS', '3/8/14.9 CAN', 1, 'CS', 37.39, 37.39, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-02-18', 'Lakeshore Beverage', 666.12, 'invoice', '543833', NULL, 0, 666.12, 0, 666.12, 'Invoice 543833 · 8 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581225', 'CUT ESP MARTIN', '6/4/12', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 3, 'CS', 59.26, 177.78, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581209', 'CUT VOD TRANS', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-581115', 'CUT VODKA MULE', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (8, 'LSB-581202', 'CUT WHITE RUSS', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-02-25', 'Lakeshore Beverage', 151.5, 'invoice', '556086', NULL, 0, 151.5, 0, 151.5, 'Invoice 556086 · 2 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-88016', 'SHINER BOCK', '24/16 CAN', 5, 'CS', 28.3, 141.5, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-03-25', 'Lakeshore Beverage', 197.13, 'invoice', '108412', NULL, 0, 197.13, 0, 197.13, 'Invoice 108412 · 7 items · Total worked out from Lakeshore running account balance on later receipts. An invoice of about $507.91 from mid-March is not in the photos.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80517', 'BHC BLUE RASPB', '4/6/12 CAN', 1, 'CS', 35.38, 35.38, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-80516', 'BHC TROP MANGO', '4/6/12 CAN', 1, 'CS', 38.48, 38.48, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-11182', 'BUD', '18/16 CAN', 1, 'CS', 18.23, 18.23, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-02462', 'GUINNESS', '3/8/14.9 CAN', 1, 'CS', 37.39, 37.39, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-88016', 'SHINER BOCK', '24/16 CAN', 1, 'CS', 28.3, 28.3, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-07414', 'STELLA', '2/12/11.2 BTL', 1, 'CS', 29.35, 29.35, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-03-25', 'Lakeshore Beverage', 976.68, 'invoice', '108413', NULL, 0, 976.68, 0, 976.68, 'Invoice 108413 · 11 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581225', 'CUT ESP MARTIN', '6/4/12', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 3, 'CS', 54.26, 162.78, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581214', 'CUT PINE MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (8, 'LSB-581113', 'CUT TIKI MAI T', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (9, 'LSB-581209', 'CUT VOD TRANS', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (10, 'LSB-581115', 'CUT VODKA MULE', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (11, 'LSB-581202', 'CUT WHITE RUSS', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-04-01', 'Lakeshore Beverage', 335.56, 'invoice', '121399', NULL, 0, 335.56, 0, 335.56, 'Invoice 121399 · 5 items · Total worked out from Lakeshore running account balance on later receipts')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581214', 'CUT PINE MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-SERVICE-CHARGE', 'SERVICE CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-04-08', 'Lakeshore Beverage', 274.39, 'invoice', '133606', NULL, 0, 274.39, 0, 274.39, 'Invoice 133606 · 6 items · Total from the items only, since the bottom of the receipt is not in the photo. The bottom of this receipt is not in the photo, so a $10 service charge may be missing.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-80505', 'BHC BIG JAM', '4/6/12 CAN', 2, 'CS', 38.48, 76.96, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-80517', 'BHC BLUE RASPB', '4/6/12 CAN', 1, 'CS', 35.38, 35.38, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-92544', 'GI 312 URBAN', '6/4/16 CAN', 1, 'CS', 38.71, 38.71, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-02462', 'GUINNESS', '3/8/14.9 CAN', 1, 'CS', 37.39, 37.39, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-88016', 'SHINER BOCK', '24/16 CAN', 2, 'CS', 28.3, 56.6, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-07414', 'STELLA', '2/12/11.2 BTL', 1, 'CS', 29.35, 29.35, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-04-08', 'Lakeshore Beverage', 651.12, 'invoice', '133607', NULL, 0, 651.12, 0, 651.12, 'Invoice 133607 · 10 items · Total from the items only, since the bottom of the receipt is not in the photo. The photo ends at White Russian, so there may be more items below it.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'LSB-581225', 'CUT ESP MARTIN', '6/4/12', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (2, 'LSB-581227', 'CUT LEMON DROP', '6/4/12', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (3, 'LSB-581114', 'CUT LIME MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (4, 'LSB-581201', 'CUT LONG ISLAN', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (5, 'LSB-581203', 'CUT MANGO MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (6, 'LSB-581214', 'CUT PINE MARG', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (7, 'LSB-581206', 'CUT STRAW MARG', '6/4/12 CAN', 2, 'CS', 54.26, 108.52, 'alcohol', 'bar', '20091', '151120'),
  (8, 'LSB-581113', 'CUT TIKI MAI T', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (9, 'LSB-581115', 'CUT VODKA MULE', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120'),
  (10, 'LSB-581202', 'CUT WHITE RUSS', '6/4/12 CAN', 1, 'CS', 54.26, 54.26, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-11-18', 'Kloss Distributing', 1251.62, 'invoice', '10251838', NULL, 0, 1251.62, 0, 1251.62, 'Invoice 10251838 · 22 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'KLS-2676', 'Angry Crisp 16oz Cn', NULL, 2, 'CS', 37.68, 75.36, 'alcohol', 'bar', '20091', '151120'),
  (2, 'KLS-2207', 'Blue Moon 16oz Cn', NULL, 1, 'CS', 34.81, 34.81, 'alcohol', 'bar', '20091', '151120'),
  (3, 'KLS-4064', 'Carbliss Vdk Lemon Lime 4pk Cn', NULL, 1, 'CS', 44.82, 44.82, 'alcohol', 'bar', '20091', '151120'),
  (4, 'KLS-4027', 'Carbliss Vdk Peach 4pk Cn', NULL, 1, 'CS', 44.82, 44.82, 'alcohol', 'bar', '20091', '151120'),
  (5, 'KLS-4044', 'Carbliss Vdk Pineapple 4pk Cn', NULL, 1, 'CS', 44.82, 44.82, 'alcohol', 'bar', '20091', '151120'),
  (6, 'KLS-2043', 'Coors Banquet 15pk Alum Bt', NULL, 8, 'CS', 14.77, 118.16, 'alcohol', 'bar', '20091', '151120'),
  (7, 'KLS-2027', 'Coors Lt 16oz 12pk Cn', NULL, 2, 'CS', 23.31, 46.62, 'alcohol', 'bar', '20091', '151120'),
  (8, 'KLS-7426', 'Corona Extra 16oz Cn', NULL, 1, 'CS', 34.61, 34.61, 'alcohol', 'bar', '20091', '151120'),
  (9, 'KLS-7017', 'Dos XX Lager 16oz Cn', NULL, 2, 'CS', 35.3, 70.6, 'alcohol', 'bar', '20091', '151120'),
  (10, 'KLS-7446', 'Modelo Especial 16oz Cn', NULL, 2, 'CS', 34.61, 69.22, 'alcohol', 'bar', '20091', '151120'),
  (11, 'KLS-7202', 'REV Anti-Hero IPA 16oz Cn', NULL, 1, 'CS', 45.95, 45.95, 'alcohol', 'bar', '20091', '151120'),
  (12, 'KLS-7641', 'REV Cold Time 16oz Cn', NULL, 2, 'CS', 30.1, 60.2, 'alcohol', 'bar', '20091', '151120'),
  (13, 'KLS-7250', 'REV Fistmas Ale 6pk Cn', NULL, 1, 'CS', 35.43, 35.43, 'alcohol', 'bar', '20091', '151120'),
  (14, 'KLS-7627', 'REV X-Hero Juicy Rush 19.2oz Cn', NULL, 6, 'CS', 30.15, 180.9, 'alcohol', 'bar', '20091', '151120'),
  (15, 'KLS-2500', 'Sam Lager 6pk Bt', NULL, 1, 'CS', 34.48, 34.48, 'alcohol', 'bar', '20091', '151120'),
  (16, 'KLS-2535', 'Sam Winter Lager 6pk Bt', NULL, 1, 'CS', 34.48, 34.48, 'alcohol', 'bar', '20091', '151120'),
  (17, 'KLS-3745', 'Sierra Hazy Little 6pk Cn', NULL, 1, 'CS', 35.13, 35.13, 'alcohol', 'bar', '20091', '151120'),
  (18, 'KLS-7857', 'TH Boxcar Porter 16oz Cn', NULL, 1, 'CS', 51.8, 51.8, 'alcohol', 'bar', '20091', '151120'),
  (19, 'KLS-7841', 'TH Longsnapper 16oz Cn', NULL, 1, 'CS', 51.11, 51.11, 'alcohol', 'bar', '20091', '151120'),
  (20, 'KLS-7803', 'TH Scarlet Fire 16oz Cn', NULL, 1, 'CS', 51.8, 51.8, 'alcohol', 'bar', '20091', '151120'),
  (21, 'KLS-2706', 'Twisted Tea 16oz Cn', NULL, 2, 'CS', 39.5, 79, 'alcohol', 'bar', '20091', '151120'),
  (22, 'KLS-DELIVERY-CHARGE', 'DELIVERY CHARGE', NULL, 1, 'CS', 7.5, 7.5, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2025-12-16', 'Kloss Distributing', -126.38, 'credit', '10253244', NULL, 0, -126.38, 0, -126.38, 'Credit 10253244 · 2 items · Total printed on the invoice. Returned for restock.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'KLS-7330', 'Modelo Especial 6pk Bt', NULL, 1, 'CS', 34.48, -34.48, 'alcohol', 'bar', '20091', '151120'),
  (2, 'KLS-7202', 'REV Anti-Hero IPA 16oz Cn', NULL, 2, 'CS', 45.95, -91.9, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-01-06', 'Kloss Distributing', -167.64, 'credit', '10254279', NULL, 0, -167.64, 0, -167.64, 'Credit 10254279 · 1 item · Total printed on the invoice. Returned for restock.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'KLS-3221', 'NH Dragons Milk 19.2oz Cn', NULL, 4, 'CS', 41.91, -167.64, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-02-24', 'Kloss Distributing', 442.16, 'invoice', '10256742', NULL, 0, 442.16, 0, 442.16, 'Invoice 10256742 · 9 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'KLS-2676', 'Angry Crisp 16oz Cn', NULL, 1, 'CS', 37.68, 37.68, 'alcohol', 'bar', '20091', '151120'),
  (2, 'KLS-2043', 'Coors Banquet 15pk Alum Bt', NULL, 4, 'CS', 15.67, 62.68, 'alcohol', 'bar', '20091', '151120'),
  (3, 'KLS-2017', 'Coors Lt 16oz Cn', NULL, 2, 'CS', 25.51, 51.02, 'alcohol', 'bar', '20091', '151120'),
  (4, 'KLS-1017', 'Lite 16oz Cn', NULL, 1, 'CS', 25.51, 25.51, 'alcohol', 'bar', '20091', '151120'),
  (5, 'KLS-7485', 'Negra Modelo 24pk Bt', NULL, 1, 'CS', 29.88, 29.88, 'alcohol', 'bar', '20091', '151120'),
  (6, 'KLS-7627', 'REV X-Hero Juicy Rush 19.2oz Cn', NULL, 4, 'CS', 30.95, 123.8, 'alcohol', 'bar', '20091', '151120'),
  (7, 'KLS-2500', 'Sam Lager 6pk Bt', NULL, 2, 'CS', 34.48, 68.96, 'alcohol', 'bar', '20091', '151120'),
  (8, 'KLS-3745', 'Sierra Hazy Little 6pk Cn', NULL, 1, 'CS', 35.13, 35.13, 'alcohol', 'bar', '20091', '151120'),
  (9, 'KLS-DELIVERY-CHARGE', 'DELIVERY CHARGE', NULL, 1, 'CS', 7.5, 7.5, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-04-14', 'Kloss Distributing', 443.07, 'invoice', '10259248', NULL, 0, 443.07, 0, 443.07, 'Invoice 10259248 · 9 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'KLS-2676', 'Angry Crisp 16oz Cn', NULL, 1, 'CS', 37.68, 37.68, 'alcohol', 'bar', '20091', '151120'),
  (2, 'KLS-2043', 'Coors Banquet 15pk Alum Bt', NULL, 4, 'CS', 15.67, 62.68, 'alcohol', 'bar', '20091', '151120'),
  (3, 'KLS-2027', 'Coors Lt 16oz 12pk Cn', NULL, 1, 'CS', 23.31, 23.31, 'alcohol', 'bar', '20091', '151120'),
  (4, 'KLS-1001', 'Lite 16oz 12pk Cn', NULL, 1, 'CS', 24, 24, 'alcohol', 'bar', '20091', '151120'),
  (5, 'KLS-7446', 'Modelo Especial 16oz Cn', NULL, 2, 'CS', 34.61, 69.22, 'alcohol', 'bar', '20091', '151120'),
  (6, 'KLS-9372', 'Overtime Teq Marg 24pk Cn', NULL, 2, 'CS', 46.2, 92.4, 'alcohol', 'bar', '20091', '151120'),
  (7, 'KLS-9362', 'Overtime Vdk Watermelon 24pk Cn', NULL, 2, 'CS', 46.2, 92.4, 'alcohol', 'bar', '20091', '151120'),
  (8, 'KLS-3795', 'Sierra Big Little Cn', NULL, 1, 'CS', 31.38, 31.38, 'alcohol', 'bar', '20091', '151120'),
  (9, 'KLS-DELIVERY-CHARGE', 'DELIVERY CHARGE', NULL, 1, 'CS', 10, 10, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-04-14', 'Kloss Distributing', 236.48, 'invoice', '10259249', NULL, 0, 236.48, 0, 236.48, 'Invoice 10259249 · 7 items · Total printed on the invoice. Yuengling: 2 ordered, 1 shipped (back order).')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'KLS-2676', 'Angry Crisp 16oz Cn', NULL, 1, 'CS', 37.68, 37.68, 'alcohol', 'bar', '20091', '151120'),
  (2, 'KLS-2207', 'Blue Moon 16oz Cn', NULL, 1, 'CS', 34.81, 34.81, 'alcohol', 'bar', '20091', '151120'),
  (3, 'KLS-2832', 'Coors Banquet Lager 12pk Cn', NULL, 2, 'CS', 24, 48, 'alcohol', 'bar', '20091', '151120'),
  (4, 'KLS-2027', 'Coors Lt 16oz 12pk Cn', NULL, 1, 'CS', 23.31, 23.31, 'alcohol', 'bar', '20091', '151120'),
  (5, 'KLS-2706', 'Twisted Tea 16oz Cn', NULL, 1, 'CS', 39.5, 39.5, 'alcohol', 'bar', '20091', '151120'),
  (6, 'KLS-9216', 'White Claw Black Cherry 16oz Cn', NULL, 1, 'CS', 37.51, 37.51, 'alcohol', 'bar', '20091', '151120'),
  (7, 'KLS-4503', 'Yuengling Lager 16oz 15pk Alum Bt', NULL, 1, 'CS', 15.67, 15.67, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-05-05', 'Kloss Distributing', 179.79, 'invoice', '10260832', NULL, 0, 179.79, 0, 179.79, 'Invoice 10260832 · 5 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'KLS-2676', 'Angry Crisp 16oz Cn', NULL, 1, 'CS', 37.68, 37.68, 'alcohol', 'bar', '20091', '151120'),
  (2, 'KLS-2017', 'Coors Lt 16oz Cn', NULL, 1, 'CS', 25.51, 25.51, 'alcohol', 'bar', '20091', '151120'),
  (3, 'KLS-1542', 'Leinie Shandy Lemon 16oz Cn', NULL, 1, 'CS', 34.98, 34.98, 'alcohol', 'bar', '20091', '151120'),
  (4, 'KLS-7446', 'Modelo Especial 16oz Cn', NULL, 1, 'CS', 34.61, 34.61, 'alcohol', 'bar', '20091', '151120'),
  (5, 'KLS-4503', 'Yuengling Lager 16oz 15pk Alum Bt', NULL, 3, 'CS', 15.67, 47.01, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-06-18', 'MWR Central Warehouse', 272.78, 'invoice', 'SO-26-029103', NULL, 272.78, 0, 0, 0, 'Invoice SO-26-029103 · 10 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-20106', 'SODA: PEPSI 20 OZ', 'CS', 3, 'CS', 18.91, 56.73, 'food', 'restaurant', '20091', '151110'),
  (2, 'WH-20108', 'SODA: PEPSI: DIET 20 OZ', 'CS', 1, 'CS', 18.36, 18.36, 'food', 'restaurant', '20091', '151110'),
  (3, 'WH-20102', 'SODA: MOUNTAIN DEW 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (4, 'WH-20101', 'TEA: LIPTON: BRISK: W/LEMON 20 OZ', 'CS', 1, 'CS', 19.75, 19.75, 'food', 'restaurant', '20091', '151110'),
  (5, 'WH-20133', 'DOLE: LEMONADE 20 OZ', 'CS', 1, 'CS', 19.46, 19.46, 'food', 'restaurant', '20091', '151110'),
  (6, 'WH-20006', 'GATORADE: FRUIT PUNCH', 'CS', 2, 'CS', 18.76, 37.52, 'food', 'restaurant', '20091', '151110'),
  (7, 'WH-20009', 'GATORADE: ORANGE', 'CS', 2, 'CS', 18.76, 37.52, 'food', 'restaurant', '20091', '151110'),
  (8, 'WH-20007', 'GATORADE: GLACIER FREEZE', 'CS', 1, 'CS', 18.76, 18.76, 'food', 'restaurant', '20091', '151110'),
  (9, 'WH-20132', 'GATORADE ZERO: GLACIER CHERRY', 'CS', 1, 'CS', 18.21, 18.21, 'food', 'restaurant', '20091', '151110'),
  (10, 'WH-20025', 'WATER: 20 OZ BOTTLE', 'CS', 4, 'CS', 6.89, 27.56, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-06-24', 'MWR Central Warehouse', 136.77, 'invoice', 'SO-26-029117', NULL, 70.51, 0, 66.26, 0, 'Invoice SO-26-029117 · 5 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-30703', 'WIPES: FDSV RAYON 14 X 21.5', 'CS', 2, 'CS', 33.13, 66.26, 'supplies', 'restaurant', '20091', '701000'),
  (2, 'WH-20106', 'SODA: PEPSI 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (3, 'WH-20102', 'SODA: MOUNTAIN DEW 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (4, 'WH-20109', 'SODA: STARRY 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (5, 'WH-20025', 'WATER: 20 OZ BOTTLE', 'CS', 2, 'CS', 6.89, 13.78, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-07-08', 'MWR Central Warehouse', 235.79, 'invoice', 'SO-26-029135', NULL, 101.5, 0, 134.29, 0, 'Invoice SO-26-029135 · 7 items · Total printed on the invoice')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-20025', 'WATER: 20 OZ BOTTLE', 'CS', 4, 'CS', 6.89, 27.56, 'food', 'restaurant', '20091', '151110'),
  (2, 'WH-20132', 'GATORADE: ZERO: GLACIER CHERRY', 'CS', 2, 'CS', 18.21, 36.42, 'food', 'restaurant', '20091', '151110'),
  (3, 'WH-20008', 'GATORADE: LEMON/LIME', 'CS', 2, 'CS', 18.76, 37.52, 'food', 'restaurant', '20091', '151110'),
  (4, 'WH-30702', 'NAPKIN: DISPENSER: INTERFOLD: 2 PLY WHITE', 'CS', 1, 'CS', 46.01, 46.01, 'supplies', 'restaurant', '20091', '701000'),
  (5, 'WH-30707', 'NAPKIN: BEVERAGE', 'CS', 1, 'CS', 20.66, 20.66, 'supplies', 'restaurant', '20091', '701000'),
  (6, 'WH-30008', 'BAG: CLEAR: 60 GAL', 'CS', 2, 'CS', 25.33, 50.66, 'supplies', 'restaurant', '20091', '701000'),
  (7, 'WH-40025', 'BLEACH: GERM: CS/6', 'CS', 1, 'CS', 16.96, 16.96, 'supplies', 'restaurant', '20091', '701005')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-07-16', 'MWR Central Warehouse', 149.58, 'invoice', 'SO-26-029154', NULL, 149.58, 0, 0, 0, 'Invoice SO-26-029154 · 6 items · Total from the warehouse order history (no printed total, so the lines added up)')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-20108', 'SODA: PEPSI: DIET 20 OZ', 'CS', 2, 'CS', 18.36, 36.72, 'food', 'restaurant', '20091', '151110'),
  (2, 'WH-20109', 'SODA: STARRY 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (3, 'WH-20102', 'SODA: MOUNTAIN DEW 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (4, 'WH-20005', 'GATORADE: COOL BLUE', 'CS', 1, 'CS', 18.76, 18.76, 'food', 'restaurant', '20091', '151110'),
  (5, 'WH-20007', 'GATORADE: GLACIER FREEZE', 'CS', 1, 'CS', 18.76, 18.76, 'food', 'restaurant', '20091', '151110'),
  (6, 'WH-20008', 'GATORADE: LEMON/LIME', 'CS', 2, 'CS', 18.76, 37.52, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-08-04', 'MWR Central Warehouse', 329.6, 'invoice', 'SO-26-029195', NULL, 51.94, 0, 277.66, 0, 'Invoice SO-26-029195 · 7 items · Total from the warehouse order history (no printed total, so the lines added up)')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-40008', 'DEGREASER AP K43 (32 OZ)', 'CS', 1, 'CS', 26, 26, 'supplies', 'restaurant', '20091', '701005'),
  (2, 'WH-40015', 'ECOLAB: APEX RINSE', 'CS', 1, 'CS', 154.1, 154.1, 'supplies', 'restaurant', '20091', '701000'),
  (3, 'WH-40018', 'ECOLAB: DISHMACHINE SANITIZER', 'CS', 1, 'CS', 20.63, 20.63, 'supplies', 'restaurant', '20091', '701005'),
  (4, 'WH-20102', 'SODA: MOUNTAIN DEW 20 OZ', 'CS', 2, 'CS', 18.91, 37.82, 'food', 'restaurant', '20091', '151110'),
  (5, 'WH-30044', 'TOWEL 9.5X9 MULTI-FOLD: WHITE (TORK)', 'CS', 1, 'CS', 38.71, 38.71, 'supplies', 'restaurant', '20091', '701000'),
  (6, 'WH-30104', 'PLATE: PAPER: 9 IN', 'CS', 1, 'CS', 38.22, 38.22, 'supplies', 'restaurant', '20091', '701000'),
  (7, 'WH-20025', 'WATER: 20 OZ BOTTLE', 'CS', 2, 'CS', 7.06, 14.12, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-08-20', 'MWR Central Warehouse', 685.36, 'invoice', 'SO-26-029235', NULL, 7.06, 0, 678.3, 0, 'Invoice SO-26-029235 · 7 items · Total from the warehouse order history (no printed total, so the lines added up)')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-20025', 'WATER: 20 OZ BOTTLE', 'CS', 1, 'CS', 7.06, 7.06, 'food', 'restaurant', '20091', '151110'),
  (2, 'WH-80625', 'ENMOTION 10 IN PAPER TOWEL', 'CS', 3, 'CS', 64.35, 193.05, 'supplies', 'restaurant', '20091', '701005'),
  (3, 'WH-80626', 'CORELESS BATH TISSUE 2 PLY', 'CS', 3, 'CS', 53.4, 160.2, 'supplies', 'restaurant', '20091', '701000'),
  (4, 'WH-80627', 'PACIFIC BLUE ULTRA SOAP, FOAM', 'CS', 3, 'CS', 40.25, 120.75, 'supplies', 'restaurant', '20091', '701005'),
  (5, 'WH-90995', 'NO RINSE ALKALINE FLOOR CLEANER', 'CS', 1, 'CS', 58.96, 58.96, 'supplies', 'restaurant', '20091', '701005'),
  (6, 'WH-90996', 'RAPID DISINFECTANT CLEANER 2.5 GAL', 'CS', 1, 'CS', 74.3, 74.3, 'supplies', 'restaurant', '20091', '701005'),
  (7, 'WH-90997', 'ALKALINE BATHROOM CLEANER AND DISINFECTANT', 'CS', 1, 'CS', 71.04, 71.04, 'supplies', 'restaurant', '20091', '701005')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-08-27', 'MWR Central Warehouse', 247.19, 'invoice', 'SO-26-029253', NULL, 127.54, 0, 119.65, 0, 'Invoice SO-26-029253 · 6 items · Total from the warehouse order history (no printed total, so the lines added up)')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-50508', 'DRINK: LEMONADE: POWDER MIX', 'CS', 2, 'CS', 23.06, 46.12, 'food', 'restaurant', '20091', '151110'),
  (2, 'WH-50509', 'DRINK: FRUIT PUNCH: POWDER MIX', 'CS', 2, 'CS', 23.06, 46.12, 'food', 'restaurant', '20091', '151110'),
  (3, 'WH-30032', 'UTENSILS: KIT: K/F/S/N/S&P', 'CS', 1, 'CS', 35.42, 35.42, 'supplies', 'restaurant', '20091', '701000'),
  (4, 'WH-30104', 'PLATE: PAPER: 9 IN', 'CS', 1, 'CS', 38.22, 38.22, 'supplies', 'restaurant', '20091', '701000'),
  (5, 'WH-30702', 'NAPKIN: DISPENSER: INTERFOLD: 2 PLY WHITE', 'CS', 1, 'CS', 46.01, 46.01, 'supplies', 'restaurant', '20091', '701000'),
  (6, 'WH-20025', 'WATER: 20 OZ BOTTLE', 'CS', 5, 'CS', 7.06, 35.3, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-09-22', 'MWR Central Warehouse', 184.44, 'invoice', 'SO-26-029310', NULL, 114.88, 0, 69.56, 0, 'Invoice SO-26-029310 · 8 items · Total from the warehouse order history (no printed total, so the lines added up)')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'WH-20008', 'GATORADE: LEMON/LIME', 'CS', 1, 'CS', 18.76, 18.76, 'food', 'restaurant', '20091', '151110'),
  (2, 'WH-20009', 'GATORADE: ORANGE', 'CS', 1, 'CS', 18.76, 18.76, 'food', 'restaurant', '20091', '151110'),
  (3, 'WH-20025', 'WATER: 20 OZ BOTTLE', 'CS', 3, 'CS', 7.06, 21.18, 'food', 'restaurant', '20091', '151110'),
  (4, 'WH-20102', 'SODA: MOUNTAIN DEW 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (5, 'WH-20106', 'SODA: PEPSI 20 OZ', 'CS', 1, 'CS', 18.91, 18.91, 'food', 'restaurant', '20091', '151110'),
  (6, 'WH-20108', 'SODA: PEPSI: DIET 20 OZ', 'CS', 1, 'CS', 18.36, 18.36, 'food', 'restaurant', '20091', '151110'),
  (7, 'WH-40100', 'PENS: RETRACTABLE: BLACK: FINE', 'CS', 1, 'CS', 16.91, 16.91, 'supplies', 'restaurant', '20091', '701000'),
  (8, 'WH-91002', 'WIPES: RAYON 13.5 X 21', 'CS', 1, 'CS', 52.65, 52.65, 'supplies', 'restaurant', '20091', '701000')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-05-27', 'Mess requisition', 48.2, 'invoice', 'FY26-1191', NULL, 48.2, 0, 0, 0, 'Invoice FY26-1191 · 5 items · Total printed on the invoice. From Epicenter (cost center 20574).')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'REQ-LETTUCE-HEAD', 'LETTUCE, HEAD', 'EA', 3, 'CS', 1.3, 3.9, 'food', 'restaurant', '20091', '151110'),
  (2, 'REQ-ONION', 'ONION', 'EA', 2, 'CS', 0.72, 1.44, 'food', 'restaurant', '20091', '151110'),
  (3, 'REQ-TOMATO', 'TOMATO', 'EA', 6, 'CS', 0.96, 5.76, 'food', 'restaurant', '20091', '151110'),
  (4, 'REQ-BUN-HOT-DOG-PACK-OF-25', 'BUN, HOT DOG (PACK OF 25)', 'PK', 1, 'CS', 29, 29, 'food', 'restaurant', '20091', '151110'),
  (5, 'REQ-ITEM-5-HARD-TO-READ-ON-THE-SCAN', 'ITEM 5 (HARD TO READ ON THE SCAN)', NULL, 2, 'CS', 4.05, 8.1, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-06-09', 'Mess requisition', 232.38, 'invoice', 'FY26-1194', NULL, 0, 232.38, 0, 232.38, 'Invoice FY26-1194 · 5 items · Total printed on the invoice. Beer from Epicenter (cost center 20574) to Buckleys bar, account 151120. Thermal paper ($86.01) on the same sheet is not in its total.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'REQ-MODELO-ESPECIAL', 'MODELO ESPECIAL', 'CS', 2, 'CS', 34.61, 69.22, 'alcohol', 'bar', '20091', '151120'),
  (2, 'REQ-COORS-LIGHT-18PK', 'COORS LIGHT 18PK', 'CS', 2, 'CS', 21.48, 42.96, 'alcohol', 'bar', '20091', '151120'),
  (3, 'REQ-COORS-BANQUET', 'COORS BANQUET', 'CS', 2, 'CS', 24, 48, 'alcohol', 'bar', '20091', '151120'),
  (4, 'REQ-BLUE-MOON', 'BLUE MOON', 'CS', 1, 'CS', 34.81, 34.81, 'alcohol', 'bar', '20091', '151120'),
  (5, 'REQ-GUINNESS', 'GUINNESS', 'CS', 1, 'CS', 37.39, 37.39, 'alcohol', 'bar', '20091', '151120')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-07-08', 'Mess requisition', 124.24, 'invoice', 'FY26-1338', NULL, 124.24, 0, 0, 0, 'Invoice FY26-1338 · 3 items · Total printed on the invoice. From Epicenter. Only the total and two lines are clear on the scan.')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'REQ-DESSERT-BARS', 'DESSERT BARS', 'TRAY', 3, 'CS', 19.42, 58.26, 'food', 'restaurant', '20091', '151110'),
  (2, 'REQ-POTATO-SALAD', 'POTATO SALAD', NULL, 1, 'CS', 37.23, 37.23, 'food', 'restaurant', '20091', '151110'),
  (3, 'REQ-TOMATO-RED-ONION-COLESLAW-AND-OTHER-ITEM', 'TOMATO, RED ONION, COLESLAW AND OTHER ITEMS', NULL, 1, 'CS', 28.75, 28.75, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

WITH p AS (
  INSERT INTO public.restaurant_purchases
    (purchase_date, vendor, amount, kind, document_number, site, food_amount, alcohol_amount, supplies_amount, bar_cogs_amount, notes)
  VALUES ('2026-07-24', 'Mess requisition', 24.75, 'invoice', 'FY26-1344', NULL, 24.75, 0, 0, 0, 'Invoice FY26-1344 · 2 items · Total printed on the invoice. From Epicenter (cost center 20574).')
  ON CONFLICT (lower(vendor), kind, document_number) WHERE document_number IS NOT NULL DO NOTHING
  RETURNING id
)
INSERT INTO public.restaurant_purchase_lines
  (purchase_id, line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct)
SELECT p.id, v.line_no, v.product_number, v.description, v.pack_size, v.qty, v.unit, v.unit_price, v.extended, v.category, v.outlet, v.cost_ctr, v.gl_acct
FROM p CROSS JOIN (VALUES
  (1, 'REQ-DRESSING-RANCH', 'DRESSING, RANCH', 'GAL', 1, 'CS', 11.9, 11.9, 'food', 'restaurant', '20091', '151110'),
  (2, 'REQ-LETTUCE-HEAD', 'LETTUCE, HEAD', 'EA', 5, 'CS', 2.57, 12.85, 'food', 'restaurant', '20091', '151110')
) AS v(line_no, product_number, description, pack_size, qty, unit, unit_price, extended, category, outlet, cost_ctr, gl_acct);

NOTIFY pgrst, 'reload schema';
