// @vitest-environment node
import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "node:fs";
import { generateSf52Report, sf52Filename } from "@/lib/reports/sf52-report";
import {
  buildSf52Data,
  getSf52Action,
  composeSf52Name,
  toSf52Date,
  EMPTY_SF52_INPUTS,
  type Sf52FormInputs,
} from "@/lib/sf52/actions";
import { lookupPayRate, formatPayRate } from "@/lib/sf52/payscale";
import { RECRUITMENT_PRESETS } from "@/lib/sf52/recruitment-presets";
import type { PersonnelDetails } from "@/types/database";

// The generator fetches the fillable form from /templates/ (client-side in
// the app); for the test, serve it from disk.
beforeAll(() => {
  globalThis.fetch = (async (url: unknown) => {
    if (String(url).includes("sf52-form.pdf")) {
      return new Response(readFileSync("public/templates/sf52-form.pdf"));
    }
    throw new Error(`unexpected fetch: ${url}`);
  }) as typeof fetch;
});

const samplePd: PersonnelDetails = {
  name_last: "Smith",
  name_first: "John",
  name_middle: "A.",
  position_title: "Golf Laborer",
  position_number: "",
  pay_plan: "NA",
  occ_series: "3502",
  pay_band: "03",
  step: "01",
  hourly_rate: "19.05",
  work_schedule: "Flex",
  avg_hours: "",
  flsa: "N",
  cost_center: "74000",
};

function inputs(over: Partial<Sf52FormInputs>): Sf52FormInputs {
  return { ...EMPTY_SF52_INPUTS, proposedEffectiveDate: "2026-07-20", ...over };
}

/** Reopen generated bytes with pdf.js and collect live field values by name. */
async function readFields(blob: Blob) {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const bytes = new Uint8Array(await blob.arrayBuffer());
  const doc = await pdfjs.getDocument({ data: bytes }).promise;
  const values: Record<string, string> = {};
  let annotationCount = 0;
  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p);
    for (const ann of await page.getAnnotations()) {
      const a = ann as { fieldName?: string; fieldValue?: unknown };
      annotationCount++;
      if (a.fieldName && typeof a.fieldValue === "string" && a.fieldValue && a.fieldValue !== "Off") {
        values[a.fieldName] = a.fieldValue;
      }
    }
  }
  const numPages = doc.numPages;
  await doc.destroy();
  return { values, annotationCount, numPages };
}

describe("generateSf52Report", () => {
  it("uses PDF.js's legacy build in the Node 20 test runtime", async () => {
    const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
    expect(typeof pdfjs.getDocument).toBe("function");
  });

  it("fills the real form fields and keeps the PDF fillable + encrypted", async () => {
    const action = getSf52Action("resignation");
    const data = buildSf52Data(
      action,
      samplePd,
      inputs({
        box1: action.box1,
        reasonForResign: "Notified leadership 2 weeks prior to resignation date\nVerbal\nMoving out of state",
        dateSigned: "2026-07-01",
        forwardingAddress: "123 Main St, Anytown, IL 60000",
      }),
    );
    const { blob } = await generateSf52Report(data, "test.pdf");

    const raw = Buffer.from(await blob.arrayBuffer());
    expect(raw.subarray(0, 5).toString("latin1")).toBe("%PDF-");
    // Still the office's encrypted file (saved as an incremental update).
    expect(raw.toString("latin1")).toContain("/Encrypt");

    const { values, annotationCount, numPages } = await readFields(blob);
    expect(numPages).toBe(2);
    // All widgets still live (101 on page 1 + 13 on page 2).
    expect(annotationCount).toBe(114);

    expect(values.ActionsReq).toBe("Resignation");
    expect(values.FullName).toBe("Smith, John, A.");
    expect(values.ProposedEffectiveDate).toBe("07/20/26");
    expect(values.EffectiveDate).toBe("07/20/26"); // Part B-4 / Part E-2 shared field
    expect(values.ActionReqBy).toBe("Tyson Bruce, Golf Course Manager");
    expect(values.ActionAuthBy).toBe("Brian Weeks, MWR/N92 IPD");
    expect(values.AddntlInfo).toBe("Tyson Bruce, General Manager"); // box 3 default
    expect(values.PhoneNo).toBe("847-688-4593");
    expect(values.PayPlan1).toBe("NA");
    expect(values.OccCode1).toBe("3502");
    expect(values.GL1).toBe("03");
    expect(values["STEP-RATE1"]).toBe("01");
    expect(values.TOTALSAL1).toBe("19.05");
    expect(values.WorkSchedule).toBe("Flex");
    expect(values.DutyStationCode).toBe("00128");
    expect(values.DutyStation).toBe("Great Lakes, IL 60088");
    // Multiline values use \r separators like the office's copies.
    expect(values.ReasonforResignRetire).toBe(
      "Notified leadership 2 weeks prior to resignation date\rVerbal\rMoving out of state",
    );
    expect(values.DateSigned).toBe("07/01/26");
    expect(values.ForwardingAddress).toBe("123 Main St, Anytown, IL 60000");
    expect(values.FromPositionLocation).toBe("NAVSTA Great Lakes\rVMGC\rBLDG 8400\rMaintenance\r");
    // Signature fields and SSN/DOB stay untouched.
    expect(values.ActionReqSignature).toBeUndefined();
    expect(values.YourSignature).toBeUndefined();
    expect(values.DOB).toBeUndefined();
  }, 60000);

  it("fills a recruitment with Part D and the TO side only", async () => {
    const action = getSf52Action("recruitment");
    const data = buildSf52Data(
      action,
      samplePd,
      inputs({
        box1: action.box1,
        vice: "Jane Doe",
        toPositionTitle: "Maintenance Worker",
        toPayPlan: "NA",
        toOccSeries: "4749",
        toPayBand: "07",
        toStep: "1",
        toHourlyRate: "22.50",
        proposedSalaryRange: "$22.50",
        otherNotes: "Open for 14 days.",
      }),
    );
    const { blob } = await generateSf52Report(data, "test.pdf");
    const { values } = await readFields(blob);

    expect(values.ActionsReq).toBe("Recruitment"); // no ", vice" suffix in box 1
    expect(values.Vice).toBe("Jane Doe");
    expect(values.FullName).toBeUndefined(); // vacancy
    expect(values.EffectiveDate).toBeUndefined(); // B-4 only filled on resignations
    expect(values.ToPositionTitleNo).toBe("Maintenance Worker");
    expect(values.PayPlan2).toBe("NA");
    expect(values.OccCode2).toBe("4749");
    expect(values.GL2).toBe("07");
    expect(values["Step-Rate2"]).toBe("1");
    expect(values.TotalSal2).toBe("22.50");
    expect(values["#Recruitments"]).toBe("1");
    expect(values.AreasofConsideration).toBe("All Areas");
    expect(values.ProposedSalaryRange).toBe("$22.50");
    expect(values.RelocationAuth).toBe("No");
    expect(values.OtherNotes).toBe("Open for 14 days.");
    expect(values.PayPlan1).toBeUndefined(); // FROM side untouched
  }, 60000);
});

describe("buildSf52Data conventions", () => {
  it("formats names and dates like the office's copies", () => {
    expect(composeSf52Name(samplePd)).toBe("Smith, John, A.");
    expect(toSf52Date("2026-05-29")).toBe("05/29/26");
    expect(toSf52Date("05/29/26")).toBe("05/29/26"); // already formatted
  });

  it("defaults requested-by/authorized-by to the facility signers", () => {
    const a = getSf52Action("transfer");
    const d = buildSf52Data(a, samplePd, inputs({ box1: a.box1, partFRemarks: "Remarks." }));
    expect(d.actionReqBy).toBe("Tyson Bruce, Golf Course Manager");
    expect(d.actionAuthBy).toBe("Brian Weeks, MWR/N92 IPD");
    expect(d.partFRemarks).toBe("Remarks.");
    expect(d.effectiveDate).toBeUndefined(); // only Part E actions fill B-4
  });
});

describe("payscale", () => {
  it("matches the office's filled examples", () => {
    // Maintenance Worker NA-4749-07 step 1 = $22.50 on the real SF-52.
    expect(formatPayRate(lookupPayRate("NA", 7, 1)!)).toBe("22.50");
    // Golf Mechanic NA-08 step 1.
    expect(formatPayRate(lookupPayRate("NA", 8, 1)!)).toBe("23.37");
    expect(formatPayRate(lookupPayRate("NS", 19, 5)!)).toBe("48.10");
    expect(lookupPayRate("NF", 2, 1)).toBeNull();
    expect(lookupPayRate("NA", 16, 1)).toBeNull();
  });
});

describe("recruitment presets (N92's 2026-07 position table)", () => {
  it("matches the provided position/pay details", () => {
    const byKey = Object.fromEntries(RECRUITMENT_PRESETS.map((p) => [p.key, p]));
    expect(byKey.mechanic).toMatchObject({ title: "Mechanic", payPlan: "NA", occSeries: "5823", grade: "08", step: "01", hourlyRate: "23.37", salaryRange: "$23.37" });
    expect(byKey.laborer).toMatchObject({ title: "Laborer", payPlan: "NA", occSeries: "3502", grade: "03", step: "01", hourlyRate: "19.05", salaryRange: "$19.05" });
    expect(byKey.restaurant_manager).toMatchObject({ title: "Restaurant Manager", payPlan: "NF", occSeries: "1101", grade: "03", step: "", hourlyRate: "", salaryRange: "$55K-$60K", orgUnit: "Restaurant" });
    // NA rates agree with the 2026 wage schedule.
    expect(formatPayRate(lookupPayRate("NA", 8, 1)!)).toBe(byKey.mechanic.hourlyRate);
    expect(formatPayRate(lookupPayRate("NA", 3, 1)!)).toBe(byKey.laborer.hourlyRate);
  });

  it("a Restaurant Manager recruitment fills NF boxes, no salary box, range in Part D", async () => {
    const action = getSf52Action("recruitment");
    const p = RECRUITMENT_PRESETS.find((x) => x.key === "restaurant_manager")!;
    const data = buildSf52Data(
      action,
      null,
      inputs({
        box1: action.box1,
        toPositionTitle: p.title,
        toPayPlan: p.payPlan,
        toOccSeries: p.occSeries,
        toPayBand: p.grade,
        toStep: p.step,
        toHourlyRate: p.hourlyRate,
        proposedSalaryRange: p.salaryRange,
        orgUnit: p.orgUnit,
      }),
    );
    const { blob } = await generateSf52Report(data, "test.pdf");
    const { values } = await readFields(blob);
    expect(values.ToPositionTitleNo).toBe("Restaurant Manager");
    expect(values.PayPlan2).toBe("NF");
    expect(values.OccCode2).toBe("1101");
    expect(values.GL2).toBe("03");
    expect(values["Step-Rate2"]).toBeUndefined(); // NF has no step
    expect(values.TotalSal2).toBeUndefined(); // range goes in Part D instead
    expect(values.ProposedSalaryRange).toBe("$55K-$60K");
    expect(values.ToPositionLocation).toBe("NAVSTA Great Lakes\rVMGC\rBLDG 8400\rRestaurant\r");
  }, 60000);
});

describe("sf52Filename", () => {
  const jul7 = new Date("2026-07-07T12:00:00");

  it("employee actions: action _ last name _ title (spaces kept)", () => {
    expect(sf52Filename({ action: "Resignation", lastName: "Damian", positionTitle: "Golf Mechanic" })).toBe(
      "SF52_Resignation_Damian_Golf Mechanic.pdf",
    );
    expect(
      sf52Filename({ action: "Resignation", lastName: "Melyon", positionTitle: "Restaurant Manager" }),
    ).toBe("SF52_Resignation_Melyon_Restaurant Manager.pdf");
    // Illegal filename characters are folded to spaces.
    expect(
      sf52Filename({ action: "Transfer", lastName: "Smith", positionTitle: "Rec Aide / Cart Barn" }),
    ).toBe("SF52_Transfer_Smith_Rec Aide Cart Barn.pdf");
  });

  it("recruitments: action _ plan-grade title _ date (the office's vacancy naming)", () => {
    expect(
      sf52Filename({ action: "Recruitment", positionTitle: "Mechanic", vacancy: true, payPlan: "NA", grade: "08", now: jul7 }),
    ).toBe("SF52_Recruitment_NA-08 Mechanic_07JUL26.pdf");
    expect(
      sf52Filename({ action: "Recruitment", positionTitle: "Laborer", vacancy: true, payPlan: "NA", grade: "03", now: jul7 }),
    ).toBe("SF52_Recruitment_NA-03 Laborer_07JUL26.pdf");
    expect(
      sf52Filename({ action: "Recruitment", positionTitle: "Restaurant Manager", vacancy: true, payPlan: "NF", grade: "03", now: jul7 }),
    ).toBe("SF52_Recruitment_NF-03 Restaurant Manager_07JUL26.pdf");
    // No plan/grade typed — no dangling prefix.
    expect(sf52Filename({ action: "Recruitment", positionTitle: "Mechanic", vacancy: true, now: jul7 })).toBe(
      "SF52_Recruitment_Mechanic_07JUL26.pdf",
    );
  });
});
