/**
 * extract-889 — pull structured data from a SAM.gov "Record of Section 889
 * Representations" PDF (or photo of one) so the vendors page can create
 * a vendor record automatically.
 *
 * The form is a one-page summary printed by the SmartPay 889 tool; every
 * VMGC vendor we work with submits one. Field positions are predictable.
 *
 * Auth: signed-in user. Secrets: ANTHROPIC_API_KEY.
 *
 * Deploy:  supabase functions deploy extract-889
 *
 * Request body (JSON):
 *   { image_base64: string, media_type: "application/pdf" | "image/jpeg" | ... }
 *
 * Response:
 *   {
 *     name, dba, uei, cage,
 *     address, city_state_zip,
 *     activation_date, expiration_date,   // YYYY-MM-DD
 *     compliant: boolean,
 *     warnings: string[]
 *   }
 */
import { handleCors, jsonError, jsonResponse } from "../_shared/cors.ts";
import { getUser } from "../_shared/supabase.ts";

const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";
const MODEL = "claude-sonnet-4-20250514";
const ANTHROPIC_VERSION = "2023-06-01";
const MAX_TOKENS = 1024;
const TIMEOUT_MS = 60_000;

const EXTRACTION_PROMPT = `You are reading a Section 889 representation document so the app can
register a vendor for purchase requests. Two formats are common:

  FORMAT A — "Summary of SAM.gov Data" PDF auto-generated by the SmartPay
  889 tool. Has structured fields: legal name, DBA in parentheses, SAM.gov
  UEI, CAGE, full address, Activation Date, Expiration Date, and an
  "889 Representations Summary: COMPLIANT" (or NON-COMPLIANT) line.

  FORMAT B — "CNIC NAF PC Use of Covered Telecommunications Equipment or
  Services Representation" paper form (also titled "Section 889 form" or
  similar). Cardholder gives this to the merchant; merchant fills it in
  by hand. Has checkboxes "does" / "does not" provide covered telecom
  equipment, plus handwritten Merchant Name, Authorized Rep Name,
  Signature, and Date Signed (often handwritten in m-d-yy or m/d/yy).

Both formats satisfy 889. Return ONLY valid JSON in this exact shape —
no commentary, no markdown:

{
  "name": string | null,
  "dba": string | null,
  "uei": string | null,
  "cage": string | null,
  "address": string | null,
  "city_state_zip": string | null,
  "activation_date": string | null,
  "expiration_date": string | null,
  "date_signed": string | null,
  "form_type": "sam_gov" | "paper_merchant" | "unknown",
  "compliant": boolean,
  "warnings": string[]
}

Field rules:

- name (REQUIRED for either format):
    Format A → the legal entity name under "Summary for:". e.g. "RUSSO HARDWARE INC".
    Format B → the handwritten "Merchant Name" line. Read handwriting to your
    best ability and capitalize naturally (e.g. "Napa" → "Napa Auto Parts" if
    that's clearly what it says, otherwise keep as written like "Napa").
- dba: parenthesized trade name on Format A. null on Format B.
- uei: 12-char SAM.gov UEI on Format A. null on Format B.
- cage: 5-char CAGE code on Format A. null on Format B.
- address: street line on Format A. null on Format B.
- city_state_zip: city/state/zip line on Format A. null on Format B.
- activation_date (ISO YYYY-MM-DD): Format A's "Activation Date".
  null on Format B.
- expiration_date (ISO YYYY-MM-DD): Format A's "Expiration Date" line —
  CRITICAL since the app gates PRs on this. For Format B, set to
  date_signed + 365 days (one year from signing) since CNIC NAF PC paper
  reps are renewed annually.
- date_signed (ISO YYYY-MM-DD): for Format B, the handwritten "Date Signed"
  line. Handwritten dates can use slashes or dashes — convert "4-22-26",
  "4/22/26", "April 22, 2026" all to "2026-04-22". For Format A, leave null
  (the activation date is the equivalent).
- form_type: "sam_gov" if Format A, "paper_merchant" if Format B,
  "unknown" if you can't tell.
- compliant:
    Format A → true iff "889 Representations Summary: COMPLIANT" appears
    (similar variants like "NOT EXCLUDED" also count).
    Format B → true iff the "does not" checkbox in Section 2 is the one
    marked. The "does" checkbox marked means the merchant SELLS covered
    telecom equipment, which is NON-COMPLIANT for our purchases.
- warnings: brief strings for any field you couldn't read with high
  confidence (e.g. "Date Signed handwriting hard to read"). Empty array
  [] if everything was clear.

If the document doesn't look like either format, return all nulls and
add "doesn't appear to be a 889 representation" to warnings, with
form_type = "unknown".

Empty string is not allowed — use null. Do not invent values.`;

interface AnthropicTextBlock {
  type: "text";
  text: string;
}
interface AnthropicMessageResponse {
  content: AnthropicTextBlock[];
  stop_reason: string;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return handleCors();
  if (req.method !== "POST") return jsonError("Method not allowed", 405);

  try {
    const user = await getUser(req);
    if (!user) return jsonError("Unauthorized", 401);

    const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY");
    if (!ANTHROPIC_API_KEY) {
      return jsonError("ANTHROPIC_API_KEY not configured", 500);
    }

    const body = await req.json();
    const imageBase64: string | undefined = body.image_base64;
    const mediaType: string | undefined = body.media_type;
    if (!imageBase64 || !mediaType) {
      return jsonError("Missing image_base64 or media_type", 400);
    }

    const isPdf = mediaType === "application/pdf";
    const allowedImage = ["image/jpeg", "image/png", "image/gif", "image/webp"];
    if (!isPdf && !allowedImage.includes(mediaType)) {
      return jsonError(
        `Unsupported file type: ${mediaType}. Use PDF, JPEG, PNG, GIF, or WebP.`,
        400,
      );
    }

    const userBlock = isPdf
      ? {
          type: "document" as const,
          source: {
            type: "base64" as const,
            media_type: "application/pdf" as const,
            data: imageBase64,
          },
        }
      : {
          type: "image" as const,
          source: {
            type: "base64" as const,
            media_type: mediaType,
            data: imageBase64,
          },
        };

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), TIMEOUT_MS);

    let claudeResp: Response;
    try {
      claudeResp = await fetch(ANTHROPIC_API_URL, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": ANTHROPIC_API_KEY,
          "anthropic-version": ANTHROPIC_VERSION,
          ...(isPdf ? { "anthropic-beta": "pdfs-2024-09-25" } : {}),
        },
        body: JSON.stringify({
          model: MODEL,
          max_tokens: MAX_TOKENS,
          system: EXTRACTION_PROMPT,
          messages: [
            {
              role: "user",
              content: [
                userBlock,
                {
                  type: "text",
                  text: "Extract the vendor record from this 889 summary.",
                },
              ],
            },
          ],
        }),
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timeout);
    }

    if (!claudeResp.ok) {
      const text = await claudeResp.text();
      console.error("[extract-889] Anthropic error:", claudeResp.status, text);
      return jsonError(`Anthropic API error (${claudeResp.status})`, 502);
    }

    const data = (await claudeResp.json()) as AnthropicMessageResponse;
    const reply = data.content?.find((c) => c.type === "text")?.text || "";

    const parsed = parseJsonReply(reply);
    if (!parsed) {
      return jsonResponse({
        name: null,
        dba: null,
        uei: null,
        cage: null,
        address: null,
        city_state_zip: null,
        activation_date: null,
        expiration_date: null,
        compliant: false,
        warnings: ["Couldn't parse model output as JSON. Try a clearer image."],
      });
    }

    return jsonResponse(parsed);
  } catch (err) {
    console.error("[extract-889] Unexpected error:", err);
    const message = err instanceof Error ? err.message : "Unknown error";
    return jsonError(message, 500);
  }
});

function parseJsonReply(reply: string): unknown | null {
  const trimmed = reply.trim();
  const fenceMatch = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/);
  const candidate = fenceMatch ? fenceMatch[1] : trimmed;
  try {
    return JSON.parse(candidate);
  } catch {
    const m = candidate.match(/\{[\s\S]*\}/);
    if (m) {
      try {
        return JSON.parse(m[0]);
      } catch {
        return null;
      }
    }
    return null;
  }
}
