// The bar vendor receipts transcribed from the Google Drive scans
// (supabase/data/vendor-receipts-2025-26.json) and the SQL that loads them.
// Every invoice must add up to its total, and the committed SQL must be what
// the data makes. To rewrite the SQL after changing the data:
//   UPDATE_VENDOR_SQL=1 npx vitest run src/__tests__/restaurant/vendor-receipts.test.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  classifyVendorLine,
  planVendorInvoice,
  vendorProfile,
  type PlannedVendorInvoice,
} from "@/lib/restaurant/vendor-invoice";
import { vendorInvoiceSql } from "@/lib/restaurant/vendor-invoice-sql";

interface Receipt {
  vendor: string;
  kind: "invoice" | "credit";
  document_number: string;
  purchase_date: string;
  lines: { item: string | null; description: string; pack_size: string | null; qty: number; unit_price: number; extended: number }[];
  total: number;
  total_basis: string;
  note: string | null;
}

const root = join(__dirname, "..", "..", "..");
const dataPath = join(root, "supabase", "data", "vendor-receipts-2025-26.json");
const sqlPath = join(root, "supabase", "data", "20261010_vendor_receipts_2025_26.sql");
const receipts = JSON.parse(readFileSync(dataPath, "utf8")) as Receipt[];

function plan(r: Receipt): PlannedVendorInvoice {
  const profile = vendorProfile(r.vendor);
  return planVendorInvoice({
    vendor: r.vendor,
    kind: r.kind,
    document_number: r.document_number,
    purchase_date: r.purchase_date,
    total: r.total,
    lines: r.lines.map((l) => ({ ...l, category: classifyVendorLine(l.description, profile) })),
    notes: [`Total ${r.total_basis}`, r.note].filter(Boolean).join(". "),
  });
}

const HEADER = `-- ============================================================================
-- Bar and Buckleys vendor receipts, Oct 2025 to Jul 2026 (2026-10-10).
--
-- Typed in from the scanned delivery receipts in Google Drive and checked
-- line by line against each receipt (and against the running account balance
-- Lakeshore prints on every receipt).
--   Lakeshore Beverage      27 invoices  Oct 6 2025 to Apr 8 2026
--   Kloss Distributing       5 invoices and 2 credits  Nov 2025 to May 2026
--   MWR Central Warehouse    3 invoices  Jun to Jul 2026
--   Mess requisitions        4 transfers from Epicenter  May to Jul 2026
-- Beer and liquor go to the bar (20091 / 151120). Sodas, water and food go to
-- the restaurant (20091 / 151110) and can be moved to the bar on the
-- Purchases page. Supplies are 20091 / 701000 or 701005.
--
-- This is data, not a schema change. Run it once in the Supabase SQL editor
-- after 20261007120000_bar_and_invoice_coding.sql. Running it again adds
-- nothing (an invoice already saved is skipped).
-- Generated by src/__tests__/restaurant/vendor-receipts.test.ts
-- ============================================================================
`;

function buildSql(): string {
  return `${HEADER}\n${receipts.map((r) => vendorInvoiceSql(plan(r))).join("\n\n")}\n\nNOTIFY pgrst, 'reload schema';\n`;
}

describe("transcribed vendor receipts", () => {
  it("every invoice adds up to its total", () => {
    for (const r of receipts) {
      const p = plan(r);
      expect({ doc: r.document_number, difference: p.difference }).toEqual({ doc: r.document_number, difference: 0 });
      // Each line is qty × (price after discount), to the cent.
      for (const l of r.lines) {
        expect({ doc: r.document_number, line: l.description, ext: Math.round(l.qty * l.unit_price * 100) / 100 }).toEqual({
          doc: r.document_number,
          line: l.description,
          ext: l.extended,
        });
      }
    }
  });

  it("codes the beer to the bar and the warehouse sodas and supplies to the restaurant", () => {
    const byNumber = new Map(receipts.map((r) => [r.document_number, plan(r)]));
    const lakeshore = byNumber.get("393156")!;
    expect(lakeshore.row).toMatchObject({ vendor: "Lakeshore Beverage", amount: 174.64, alcohol_amount: 174.64, bar_cogs_amount: 174.64 });
    expect(lakeshore.lines.every((l) => l.category === "alcohol" && l.outlet === "bar" && l.gl_acct === "151120")).toBe(true);
    expect(lakeshore.lines[0].product_number).toBe("LSB-11182");

    const credit = byNumber.get("10253244")!;
    expect(credit.row).toMatchObject({ kind: "credit", amount: -126.38, alcohol_amount: -126.38, bar_cogs_amount: -126.38 });

    const wh = byNumber.get("SO-26-029135")!;
    expect(wh.row).toMatchObject({ food_amount: 101.5, supplies_amount: 134.29, alcohol_amount: 0, bar_cogs_amount: 0 });
    const bleach = wh.lines.find((l) => l.description.startsWith("BLEACH"))!;
    expect(bleach).toMatchObject({ category: "supplies", gl_acct: "701005" });

    const beerTransfer = byNumber.get("FY26-1194")!;
    expect(beerTransfer.row).toMatchObject({ vendor: "Mess requisition", alcohol_amount: 232.38, bar_cogs_amount: 232.38 });
  });

  it("totals what was bought from each vendor", () => {
    const sum = (v: string) =>
      Math.round(receipts.filter((r) => r.vendor === v).reduce((s, r) => s + plan(r).row.amount, 0) * 100) / 100;
    expect(receipts).toHaveLength(41);
    expect(sum("Lakeshore Beverage")).toBe(10355.69);
    expect(sum("Kloss Distributing")).toBe(2259.1);
    expect(sum("MWR Central Warehouse")).toBe(645.34);
    expect(sum("Mess requisition")).toBe(429.57);
  });

  it("the SQL file is what the data makes", () => {
    const sql = buildSql();
    if (process.env.UPDATE_VENDOR_SQL) writeFileSync(sqlPath, sql);
    expect(readFileSync(sqlPath, "utf8")).toBe(sql);
    // One statement per invoice, safe to run twice, nothing the editor chokes on.
    expect(sql.match(/ON CONFLICT \(lower\(vendor\), kind, document_number\)/g)).toHaveLength(receipts.length);
    expect(sql).not.toMatch(/\bDO \$/);
  });
});
